name: Newman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        run: newman run Restfulapidev.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export newman-report.html

      - name: Upload Newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html